version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx-container
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ssl:/etc/nginx/ssl
        depends_on:
            - php
            - mysql
        networks:
            - laravel-network

    php:
        build: .
        container_name: php-container
        volumes:
            - ./:/var/www/html

        networks:
            - laravel-network

    mysql:
        image: mysql:5.7
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: 123
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
